#!/bin/bash

color_bg=0xff24273a
color_fg=0xffcdd6f4
color_cyan=0xff8bd5ca # Catppuccin Macchiato Teal
color_green=0xffa6da95 # Catppuccin Macchiato Green
color_yellow=0xffeed49f # Catppuccin Macchiato Yellow
color_orange=0xfff5a97f # Catppuccin Macchiato Peach
color_red=0xffed8796 # Catppuccin Macchiato Red
color_purple=0xffc6a0f6 # Catppuccin Macchiato Mauve
color_blue=0xff8aadf4 # Catppuccin Macchiato Blue

bar=(
  position=top
  height=32
  margin=10
  corner_radius=6
  color=0x001e2030
)

sketchybar --bar "${bar[@]}"

default=(
  padding_left=0
  padding_right=0
  icon.font="SF Pro:Light:16"
  label.font="FiraCode Nerd Font Mono:Regular:12.0"
  icon.color=$color_fg
  label.color=$color_fg
  icon.padding_left=3
  icon.padding_right=3
  label.padding_left=0
  label.padding_right=0
  background.color=$color_bg
  background.height=26
  background.corner_radius=6
)
sketchybar --default "${default[@]}"

## Spaces ##
space_item=(
  icon.highlight_color=$color_bg
  icon.font="FiraCode Nerd Font Mono:Regular:10.0"
  icon.padding_left=4
  icon.padding_right=3
  label.highlight_color=$color_bg
  label.font="mac-app-glyphs:Regular:16.0"
  label.padding_left=0
  label.padding_right=1
  background.height=20
  background.corner_radius=5
  background.drawing=off
  padding_left=3
  padding_right=1
)

space_colors=($color_cyan, $color_yellow, $color_blue, $color_orange, $color_purple)

sketchybar --add event aerospace_workspace_change \
           --add event aerospace_moved_node_to_workspace

sketchybar --add item space.start left --set space.start background.drawing=off width=0
space_index=0
for space_info_str in $(aerospace list-workspaces --all --format "%{monitor-appkit-nsscreen-screens-id}:%{workspace}"); do
  IFS=":" read -r -a space_info_arr <<<"$space_info_str"
  space_monitor=${space_info_arr[0]}
  space_id=${space_info_arr[1]}
  space_color=${space_colors[space_index % ${#space_colors[@]}]}

  sketchybar --add item "space.$space_id" left \
    --subscribe "space.$space_id" \
      space_windows_change \
      aerospace_workspace_change \
      aerospace_moved_node_to_workspace \
      display_change \
    --set "space.$space_id" \
    icon="$space_id" \
    icon.color="$space_color" label.color="$space_color" background.color="$space_color" "${space_item[@]}" \
    display="$space_monitor" \
    click_script="aerospace workspace \"$space_id\"" \
    script="\"$CONFIG_DIR/scripts/update_space.sh\" \"$space_id\""

  ((space_index++))
done

sketchybar --move space.0 after space.9

sketchybar --add item space.end left \
  --set space.end background.drawing=off width=0 \
  --add bracket spaces_bracket space.start space.end

## Clock ##
clock_item=(
  label.padding_right=6
)
sketchybar --add item clock right \
  --set clock \
  "${clock_item[@]}" \
  update_freq=10 \
  script="$CONFIG_DIR/scripts/update_clock.sh"

## Battery ##
battery_item=(
  label.padding_left=3
  label.padding_right=6
  padding_right=6
)
sketchybar --add item battery right \
  --set battery \
  "${battery_item[@]}" \
  update_freq=60 \
  script="$CONFIG_DIR/scripts/update_battery.sh"

## Dark Mode toggle ##
darkmode_item=(
  icon="􂱣"
  padding_right=6
)
sketchybar --add item darkmode right \
  --set darkmode \
  "${darkmode_item[@]}" \
  click_script="osascript -e 'tell app \"System Events\" to tell appearance preferences to set dark mode to not dark mode'"

sketchybar --update
